version: "2"
services:
  mongo:
    build:
        context: .
        dockerfile: dockerfiles/dockerfile_mongo
    ports:
      - "28000:27017"

  web:
    build:
        context: .
        dockerfile: dockerfiles/dockerfile_flask
    ports:
      - "5005:5000"
    volumes:
      - .:/code
    environment:
      MONGO_SERVER: mongo
      MONGO_PORT: 27017
      DATABASE_NAME:
      WEB_SERVER: 0.0.0.0
      WEB_PORT: 5000