# use image
FROM python:3.6


# run configuration
RUN pip install Flask==0.11.1
RUN pip install pymongo==3.3.0

# copy my code to the container
ADD . /opt/flask_server
WORKDIR /opt/flask_server

# expose port
EXPOSE 5000

# start app
CMD [ "python", "-u", "./run_webserver.py" ]